export const doctors = [
  {
    id: "1",
    name: "Dr. Prerna Narang",
    specialty: "Infertility",
    gender: "Male",
    experience: 7,
    rating: 4.5,
    languages: ["English", "Hindi", "Marathi"],
    consultationTypes: [
      { type: "Video Consultation", price: "₹800" },
      { type: "Chat Consultation", price: "Free" },
    ],
    image: "/female-doctor-stethoscope.png",
    qualification: "MBBS, MD Obstetrics",
    followers: 860,
    following: 18,
    reviews: 250,
    consultationFee: 899,
    about:
      "Hello I am Dr. Prerna Narang, a gynaecologist based in Bangalore Hospital. I work with utmost care for my patients and ensure they feel confident about their medical procedures. Completed my graduation in Gynaecologist Medicine from the prestigious institute.",
    socialLinks: ["facebook", "instagram", "youtube", "twitter"],
    specializations: ["Women's Health", "Skin Care", "Immunity", "Hair Care"],
    concerns: [
      "Skin Treatment",
      "Pregnancy",
      "Period Doubts",
      "Endometriosis",
      "Pelvic Pain",
      "Ovarian Cysts",
      "+ 5 More",
    ],
    experience_details: [
      { position: "Senior Doctor", hospital: "Bangalore Medical Centre", years: "2016-PRESENT" },
      { position: "Junior Doctor", hospital: "Midtown Medical Clinic", years: "2010-2015" },
    ],
    reviews_data: [
      {
        author: "Alicent Hightower",
        rating: 5,
        consultedFor: "Skin care",
        text: "Might be bit early to confirm but yes I can see noticeable difference in my hairfall. will write again after using it for longer periods",
        date: "20 January 2023",
        avatar: "/diverse-female-avatar.png",
      },
      {
        author: "Alicent Hightower",
        rating: 5,
        consultedFor: "Pregnancy",
        text: "Might be bit early to confirm but yes I can see noticeable difference. will write again after using it for longer periods",
        date: "20 January 2023",
        avatar: "/diverse-female-avatar.png",
      },
    ],
  },
  {
    id: "2",
    name: "Dr. Bruce Willis",
    specialty: "Gynecologist",
    gender: "Female",
    experience: 7,
    rating: 4.2,
    languages: ["English", "Hindi", "Marathi"],
    consultationTypes: [
      { type: "Video Consultation", price: "₹800" },
      { type: "Chat Consultation", price: "Free" },
    ],
    image: "/male-doctor-stethoscope.png",
    qualification: "MBBS, MD Gynecology",
    followers: 950,
    following: 22,
    reviews: 302,
    consultationFee: 999,
    about:
      "Hello I am Dr. Bruce Willis, a experienced gynecologist with specialization in women's health. I am committed to providing the best care and support to my patients throughout their medical journey.",
    socialLinks: ["facebook", "instagram", "youtube", "twitter"],
    specializations: ["Women's Health", "Skin Care", "Immunity", "Hair Care"],
    concerns: [
      "Skin Treatment",
      "Pregnancy",
      "Period Doubts",
      "Endometriosis",
      "Pelvic Pain",
      "Ovarian Cysts",
      "+ 5 More",
    ],
    experience_details: [
      { position: "Senior Doctor", hospital: "Bangalore Medical Centre", years: "2016-PRESENT" },
      { position: "Junior Doctor", hospital: "Midtown Medical Clinic", years: "2010-2015" },
    ],
    reviews_data: [
      {
        author: "Alicent Hightower",
        rating: 5,
        consultedFor: "Skin care",
        text: "Might be bit early to confirm but yes I can see noticeable difference in my hairfall. will write again after using it for longer periods",
        date: "20 January 2023",
        avatar: "/diverse-female-avatar.png",
      },
      {
        author: "Alicent Hightower",
        rating: 5,
        consultedFor: "Pregnancy",
        text: "Might be bit early to confirm but yes I can see noticeable difference. will write again after using it for longer periods",
        date: "20 January 2023",
        avatar: "/diverse-female-avatar.png",
      },
    ],
  },
  {
    id: "3",
    name: "Dr. Prerna Narang",
    specialty: "Orthopedics",
    gender: "Female",
    experience: 7,
    rating: 4.5,
    languages: ["English", "Hindi", "Marathi"],
    consultationTypes: [
      { type: "Video Consultation", price: "₹800" },
      { type: "Chat Consultation", price: "Free" },
    ],
    image: "/male-orthopedic-doctor.png",
    qualification: "MBBS, MS Orthopedics",
    followers: 1200,
    following: 35,
    reviews: 425,
    consultationFee: 1099,
    about:
      "Hello I am Dr. Prerna Narang, an experienced orthopedic surgeon with over 7 years of practice. I specialize in bone and joint health, providing comprehensive care for musculoskeletal conditions.",
    socialLinks: ["facebook", "instagram", "youtube", "twitter"],
    specializations: ["Women's Health", "Skin Care", "Immunity", "Hair Care"],
    concerns: ["Bone Treatment", "Joint Pain", "Sports Injury", "Fractures", "Arthritis", "Back Pain", "+ 5 More"],
    experience_details: [
      { position: "Senior Doctor", hospital: "Bangalore Medical Centre", years: "2016-PRESENT" },
      { position: "Junior Doctor", hospital: "Midtown Medical Clinic", years: "2010-2015" },
    ],
    reviews_data: [
      {
        author: "Alicent Hightower",
        rating: 5,
        consultedFor: "Orthopedics",
        text: "Excellent care and professional approach. The doctor was very knowledgeable and took time to explain the treatment.",
        date: "20 January 2023",
        avatar: "/male-avatar.png",
      },
    ],
  },
]
